# Generated by Django 3.1.6 on 2021-02-16 15:18

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiopage",
            name="body",
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="videopage",
            name="body",
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
