version: '3'

services:
  db:
    image: postgres:12.0
    ports:
     - "5432:5432"
  web:
    build: .
    volumes:
      - ./:/app
    depends_on:
     - db
    ports:
     - "8000:8000"
    # Closely match prod server
    # command: pipenv run gunicorn config.wsgi:application --bind 0.0.0.0:8000 --timeout 3600 --workers 3 --reload --capture-output
    # Server for better debugging output
    command: poetry run python manage.py runserver 0.0.0.0:8000
    restart: on-failure
    stdin_open: true
    tty: true
    env_file:
      - .env
