# Generated by Django 3.1.6 on 2021-02-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaggedSuitableForLearningResourceTag',
            new_name='TaggedResearchGuide',
        ),
        migrations.AddField(
            model_name='researchguidepage',
            name='source_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
