# Generated by Django 3.1.6 on 2021-04-01 10:40

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchguidepage",
            name="body",
            field=wagtail.core.fields.RichTextField(default=""),
            preserve_default=False,
        ),
    ]
