# Generated by Django 3.1.6 on 2021-02-05 14:22

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20210205_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchguidepage',
            name='research_guide_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='research.TaggedResearchGuide', to='research.ResearchGuideTag', verbose_name='Tags'),
        ),
    ]
