# Generated by Django 3.1.6 on 2021-04-01 14:24

from django.db import migrations
import tna.richtext.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_researchguidepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchguidepage',
            name='body',
            field=tna.richtext.fields.RichTextField(blank=True),
        ),
    ]
