# Generated by Django 3.1.6 on 2021-02-16 15:18

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresourcepage',
            name='body',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
