# Generated by Django 3.1.6 on 2021-02-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20210203_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningresourcepage',
            name='date_published',
        ),
        migrations.AddField(
            model_name='learningresourcepage',
            name='potential_activities',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningresourcepage',
            name='sub_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningresourcepage',
            name='suggested_inquiry_question',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
