# Generated by Django 3.1.6 on 2021-02-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20210204_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresourcepage',
            name='potential_activities',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='learningresourcepage',
            name='suggested_inquiry_question',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
