# Generated by Django 3.1.6 on 2021-02-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20210204_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresourcepage',
            name='potential_activities',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='learningresourcepage',
            name='suggested_inquiry_question',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
