# Generated by Django 3.1.6 on 2021-02-02 10:28

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='file',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='content_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='collections.TaggedCategoryBlogPageItem', to='collections.CategoryTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='theme_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='collections.TaggedThemeBlogPageItem', to='collections.ThemeTag', verbose_name='Tags'),
        ),
    ]
