# Generated by Django 3.1.6 on 2021-03-18 15:36

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0003_auto_20210318_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='records',
        ),
        migrations.CreateModel(
            name='CategoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='collections.category')),
                ('record', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='collections.record')),
            ],
        ),
    ]
