# Generated by Django 3.1.6 on 2021-02-02 15:17

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0003_auto_20210202_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenthubpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph_with_podcast', wagtail.core.blocks.StructBlock([('paragraph', wagtail.core.blocks.RichTextBlock()), ('podcast', wagtail.snippets.blocks.SnippetChooserBlock(target_model='collections.Audio'))]))], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contenthubpage',
            name='sub_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
