# Generated by Django 3.1.6 on 2022-03-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('collections', '0004_add_results_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedcategorycontenthubpageitem',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedcategorycontenthubpageitem',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='taggedthemecontenthubpageitem',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedthemecontenthubpageitem',
            name='tag',
        ),
        migrations.DeleteModel(
            name='ContentHubPage',
        ),
        migrations.DeleteModel(
            name='TaggedCategoryContentHubPageItem',
        ),
        migrations.DeleteModel(
            name='TaggedThemeContentHubPageItem',
        ),
    ]
