# Generated by Django 3.1.6 on 2021-03-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0004_auto_20210318_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorerpage',
            name='introduction',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
