# Generated by Django 3.1.6 on 2021-03-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0007_record_held_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(max_length=240),
        ),
    ]
