# Generated by Django 3.1.6 on 2021-02-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('collections', '0007_auto_20210203_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='content_tags',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='theme_tags',
        ),
        migrations.RemoveField(
            model_name='taggedcategoryblogpageitem',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedcategoryblogpageitem',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='taggedthemeblogpageitem',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedthemeblogpageitem',
            name='tag',
        ),
        migrations.DeleteModel(
            name='BlogIndexPage',
        ),
        migrations.DeleteModel(
            name='BlogPage',
        ),
        migrations.DeleteModel(
            name='TaggedCategoryBlogPageItem',
        ),
        migrations.DeleteModel(
            name='TaggedThemeBlogPageItem',
        ),
    ]
