# Generated by Django 3.1.6 on 2021-03-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0008_auto_20210323_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypage',
            name='introduction',
            field=models.TextField(),
        ),
    ]
