# Generated by Django 3.1.6 on 2021-02-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('collections', '0008_auto_20210205_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiopage',
            name='content_tags',
        ),
        migrations.RemoveField(
            model_name='audiopage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='audiopage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='audiopage',
            name='theme_tags',
        ),
        migrations.RemoveField(
            model_name='taggedcategoryaudioitem',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedcategoryaudioitem',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='taggedcategoryvideoitem',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedcategoryvideoitem',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='taggedthemeaudioitem',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedthemeaudioitem',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='taggedthemevideoitem',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedthemevideoitem',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='videoindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='videopage',
            name='content_tags',
        ),
        migrations.RemoveField(
            model_name='videopage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='videopage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='videopage',
            name='theme_tags',
        ),
        migrations.DeleteModel(
            name='AudioIndexPage',
        ),
        migrations.DeleteModel(
            name='AudioPage',
        ),
        migrations.DeleteModel(
            name='TaggedCategoryAudioItem',
        ),
        migrations.DeleteModel(
            name='TaggedCategoryVideoItem',
        ),
        migrations.DeleteModel(
            name='TaggedThemeAudioItem',
        ),
        migrations.DeleteModel(
            name='TaggedThemeVideoItem',
        ),
        migrations.DeleteModel(
            name='VideoIndexPage',
        ),
        migrations.DeleteModel(
            name='VideoPage',
        ),
    ]
