# Generated by Django 3.1.6 on 2022-03-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_add_insights_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insightspage',
            name='date_published',
        ),
    ]
